version: "3.8"

services:
  web:
    build: .
    command: gunicorn MTA_backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
