# Generated by Django 5.1.6 on 2025-03-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Изображение в формате PNG', upload_to='news/')),
                ('short_text_en', models.CharField(help_text='short text news', max_length=255)),
                ('short_text_ru', models.CharField(help_text='Короткий текст новости', max_length=255)),
                ('is_displayed', models.BooleanField(verbose_name='Показать')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
