# Generated by Django 5.1.6 on 2025-05-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='short_text',
            field=models.CharField(default='', help_text='Краткий текст новости', max_length=255),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_displayed',
            field=models.BooleanField(default=True, verbose_name='Показать'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_text_en',
            field=models.CharField(default='', help_text='Краткий текст новости', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_text_ru',
            field=models.CharField(default='', help_text='Краткий текст новости', max_length=255, null=True),
        ),
    ]
