# Generated by Django 5.1.6 on 2025-03-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255, verbose_name='name partner')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Наименование партнера')),
                ('logo', models.ImageField(upload_to='', verbose_name='логотип')),
                ('order', models.PositiveIntegerField(verbose_name='порядок')),
                ('is_displayed', models.BooleanField(verbose_name='Показать')),
            ],
            options={
                'verbose_name': 'Партнёр',
                'verbose_name_plural': 'Партнёры',
            },
        ),
    ]
