# Generated by Django 5.1.6 on 2025-03-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255, verbose_name='full_name')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Наименование')),
                ('staff_en', models.CharField(max_length=255, verbose_name='staff')),
                ('staff_ru', models.CharField(max_length=255, verbose_name='Должность')),
                ('picture', models.ImageField(upload_to='', verbose_name='Портрет')),
                ('order', models.PositiveIntegerField(verbose_name='Порядок')),
                ('is_displayed', models.BooleanField(verbose_name='Показать')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
