# Generated by Django 5.1.6 on 2025-03-06 10:57

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255, verbose_name='full_name')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Наименование')),
                ('logo', models.ImageField(upload_to='', verbose_name='Портрет')),
                ('picture', models.ImageField(upload_to='', verbose_name='Картинка')),
                ('short_description', models.TextField(verbose_name='Краткое описание')),
                ('dynamic_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='HTML-редактор, позволяющий вставлять изображения и текст в любом месте', null=True, verbose_name='Динамическое описание')),
                ('order', models.PositiveIntegerField(verbose_name='Порядок')),
                ('is_displayed', models.BooleanField(verbose_name='Показать')),
                ('recommended_brands', models.ManyToManyField(blank=True, help_text='Выберите бренды, которые рекомендуются после описания данного бренда', to='brand.brand', verbose_name='Рекомендуемые бренды')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
    ]
