# Generated by Django 5.1.6 on 2025-03-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='short_description',
        ),
        migrations.AddField(
            model_name='brand',
            name='short_description_en',
            field=models.TextField(default='', verbose_name='short description'),
        ),
        migrations.AddField(
            model_name='brand',
            name='short_description_ru',
            field=models.TextField(default='', verbose_name='Краткое описание'),
        ),
    ]
