# Generated by Django 5.1.6 on 2025-03-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_remove_brand_short_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
