# Generated by Django 5.1.6 on 2025-05-06 17:39

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0003_brand_brand_picture_brand_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='dynamic_description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='HTML-редактор, позволяющий вставлять изображения и текст в любом месте', null=True, verbose_name='Динамическое описание'),
        ),
        migrations.AddField(
            model_name='brand',
            name='dynamic_description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='HTML-редактор, позволяющий вставлять изображения и текст в любом месте', null=True, verbose_name='Динамическое описание'),
        ),
        migrations.AddField(
            model_name='brand',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='brand',
            name='short_description',
            field=models.TextField(default='', verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Доп. Картинка'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(upload_to='', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name_en',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name_ru',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='short_description_en',
            field=models.TextField(default='', null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='short_description_ru',
            field=models.TextField(default='', null=True, verbose_name='Краткое описание'),
        ),
    ]
